# 다차원 tensor (다차원 배열)

In [1]:
import numpy as np

## 다차원 배열의 계산 복습

In [6]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8,9],
             [10,11,12]])

print(A+B) # shape (2,3)

vec = np.array([1,2,3]) # 1차원 tensor shape: (1,)
print(A + vec) # 차원 안맞으니까 braod casting 해서 맞춰줌

print(A.dot(B.T))

[[ 8 10 12]
 [14 16 18]]
[[2 4 6]
 [5 7 9]]
[[ 50  68]
 [122 167]]
