# 다차원 tensor (다차원 배열)

In [5]:
import numpy as np

## 다차원 배열의 계산 복습

In [6]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8,9],
             [10,11,12]])

print(A+B) # shape (2,3)

vec = np.array([1,2,3]) # 1차원 tensor shape: (1,)
print(A + vec) # 차원 안맞으니까 braod casting 해서 맞춰줌

print(A.dot(B.T))

[[ 8 10 12]
 [14 16 18]]
[[2 4 6]
 [5 7 9]]
[[ 50  68]
 [122 167]]


## 다층 퍼셉트론

In [ ]:
X = np.random.randn(6,10)

# 은닉층: 10개의 입력 -> 8개의 뉴런
W1 = np.random.randn(10,8)
b1 = np.random.randn(1,8)

# 출력층: 8개의 입력 -> 4개의 클래스
W2 = np.random.randn(8,4)
b2 = np.random.randn(1,4)

# 은닉층 계산 (선형 계산  + tanh 활성화 함수)
z1 = np.dot(X,W1) + b1
result1 = np.tanh(z1)

# 출력층 계산 (선형 계산 + softmanx 활성화 함수)
z2 = np.dot(result1,W2) + b2
exp_z = np.exp(z2 - np.max(z2, axis=1, keepdims=True))
result2 = exp_z / np.sum(exp_z, axis=1, keepdims=True)

print(result2)

[[1.20860903e-01 4.95370745e-02 7.72243106e-01 5.73589162e-02]
 [2.56686412e-01 2.51704841e-01 1.14950598e-01 3.76658149e-01]
 [1.10766225e-02 3.22837848e-02 9.39347989e-01 1.72916040e-02]
 [2.85897310e-03 7.63720749e-01 4.51291154e-02 1.88291163e-01]
 [2.10830076e-02 2.32778805e-01 7.03011452e-01 4.31267357e-02]
 [1.78571753e-04 1.47076227e-01 1.99305905e-03 8.50752142e-01]]
